# Jolla-@RELEASE@-tissot-@ARCH@.ks
# generated by mic, plumbers

lang en_US.UTF-8
keyboard us
timezone --utc UTC

url --mirror=http://repo.sailfishos.org/obs/sailfishos:/4.5.0.25:/小船/latest_armv7hl/

repo --name=adaptation-tissot-@RELEASE@ --baseurl=http://repo.sailfishos.org/obs/sailfishos:/4.5.0.25:/小船/latest_armv7hl/
repo --name=adaptation-common --baseurl=http://repo.sailfishos.org/obs/sailfishos:/adaptation:/common/latest_armv7hl/
repo --name=mesa --baseurl=http://repo.sailfishos.org/obs/sailfishos:/4.5.0.25:/小船/latest_armv7hl/
repo --name=sailfishos-asexternal --baseurl=http://repo.sailfishos.org/obs/home:/sailfishos_asexternal:/asexternal:/devel/latest_armv7hl/

part / --size=3000 --fstype=ext4
part /boot --size=200 --fstype=ext2
part /home --size=4000 --fstype=ext4

packages
sailfish-version
sailfish-version-4.5.0.25
pattern:sailfish
pattern:sailfish-devel
pattern:sailfish-common
pattern:sailfish-adaptation-tissot
zip
openssh-server
vim
tar
git
curl
wget
mesa-dri-driver
mesa-egl
libhybris
droid-hal-tissot
droid-hal-hw-params-tissot
droid-hal-tools-tissot
ngfd-plugin-droid-vibrator-tissot
pulseaudio-modules-droid-hidl-tissot
sensorfw-qt5-hybris-tissot
libgbinder
gbinder
